name: CI


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:

  test-build:
    name: Run tests
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test examples
      run: |
        DOWNLOAD_SAMPLE_DATA=1 DOWNLOAD_GROUND_TRUTH=1 pytest -s tests
